Dir::Etc::parts "/tmp/verzel-firefox-apt/empty";
Dir::Etc::main "/dev/null";
Dir::Etc::sourcelist "/tmp/verzel-firefox-apt/sources.list";
Dir::Etc::sourceparts "-";
Dir::State::lists "/tmp/verzel-firefox-apt/lists";
Dir::Cache::archives "/tmp/verzel-firefox-apt/archives";
Dir::State::status "/var/lib/dpkg/status";
Debug::NoLocking "true";
